# _config.yml

# Site settings
title: "Konstantinos Billis"
description: "Bioinformatics · Data Science · Machine Learning"
email: yourname@email.com  # Replace with your actual email
theme: minima
github_username: kbillis
minimal_mistakes_skin: dark
search: true

# Timezone
timezone: Europe/Zurich

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"

# Output settings
permalink: /:categories/:title/
paginate: 5
paginate_path: "/blog/page:num/"

# Include additional folders
include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author details
author:
  name   : "Konstantinos (Kostas) Billis, PhD"
  avatar : "/assets/images/Gemini_Generated_Image_f4kebdf4kebdf4ke.png"  # Make sure this image exists or comment this line out
  bio    : "Computational biologist and data expert working at the intersection of bioinformatics, HPC pipelines and healthcare."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://kbillis.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kbillis"
    - label: "Google Scholar"
      icon: "fab fa-fw fa-google-scholar"
      url: "https://scholar.google.co.uk/citations?hl=en&user=YsQgBgUAAAAJ&view_op=list_works&sortby=pubdate"  # Replace with your actual Google Scholar URL
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/konstantinos-billis-phd-baa23a22/"  # Replace

# Footer links
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kbillis"

# Defaults
defaults:
  - scope:
      path: "_about"
      type: about
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Archives
category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
